/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.pharmacy.view;
import javax.swing.JOptionPane;
import org.pharmacy.model.*;
import org.pharmacy.controller.*;
import org.pharmacy.util.*;
/**
 *
 * @author DELL
 */
public class customerDetails extends javax.swing.JInternalFrame {

    private String customername,customeraddress;
    private int cid,age;
    /** Creates new form customerDetails */
    public customerDetails() {
        initComponents();
    }

    public void addCustomer()
    {
        customername=jTextField_CustomerName.getText();
        customeraddress=jTextField_Address1.getText();
        age=Integer.parseInt(jTextField_Age.getText().toString());
        
        customers c=new customers();
        c.setCustomerName(customername);
        c.setCustomerAddress(customeraddress);
        c.setAge(age);
        PharmacyDAO PDAO=new PharmacyDAO();
      int count=PDAO.customers(c);
      if(count>0)
      {
     cid=PDAO.customersInfo(c);
          if(cid>0)
          {
                        JOptionPane.showMessageDialog(null,"Done");
          }
         // clearFields();
      }
      customerUtil.customerid=cid;
      customerUtil.customerName=customername;
      customerUtil.customerAddress=customeraddress;
      customerUtil.age=age;
    }
    public void clearfields()
    {
        jTextField_CustomerName.setText("");
        jTextField_Address1.setText("");
        jTextField_Age.setText("");
    }
//    public void NewSalesEntry()
//{
//     SalesBillingOp cd=new SalesBillingOp();
//        jDesktopPane1.add(cd);
//        cd.setVisible(true);
//}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Enter = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_CustomerName = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Address1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Customer Info ");

        jPanel1.setBackground(new java.awt.Color(20, 130, 220));

        jButton_Enter.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Enter.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Enter.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Enter.setText("Enter");
        jButton_Enter.setBorder(null);
        jButton_Enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnterActionPerformed(evt);
            }
        });

        jButton_Clear.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Clear.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(null);
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(20, 130, 220));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Age");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Customer Name");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Address");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 40));

        jTextField_CustomerName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(jTextField_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 40));

        jTextField_Age.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, 40));

        jTextField_Address1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(jTextField_Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Clear)
                    .addComponent(jButton_Enter))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
clearfields();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnterActionPerformed
addCustomer();
dispose();

    }//GEN-LAST:event_jButton_EnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Enter;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField_Address1;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_CustomerName;
    // End of variables declaration//GEN-END:variables

}
