/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pharmacy.view;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import javax.swing.event.*;
import org.pharmacy.controller.LoginDAO;
import org.pharmacy.controller.LoginDUO;
import org.pharmacy.model.Login;
import org.pharmacy.util.Global;
/**
 *
 * @author DELL
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    CardLayout c;

    public LoginFrame() {
        initComponents();
        c= (CardLayout)(jPanel_Main.getLayout());
    }
public void adminLogin()
{
    String username=jTextField_User1.getText();
        String password=new String(jPasswordField_Pass1.getText());
        
          try
                          {
                               String pssword=password;
   MessageDigest md= MessageDigest.getInstance("MD5");
   byte[] hashInBytes =md.digest(pssword.getBytes(StandardCharsets.UTF_8));
   
   StringBuilder sb= new StringBuilder();
   for(byte b : hashInBytes)
   {
       sb.append(String.format("%02x", b));
      // System.out.println(sb.toString());
       password=sb.toString();
   }
 //  System.out.println(password);
                          }
                          catch(Exception e)
                          {
                              System.out.println(e);
                          }
  ///Encrption
      
        Login u=new Login();
        u.setUsername(username);
        u.setPassword(password);
        LoginDAO uli=new LoginDAO();
        int count=uli.verifyUser(u);
        System.out.println(count);
        if(count>0)
        {
           
            JOptionPane.showMessageDialog(null,"Login Successful");
            Global.user=username;
            Global.uid=count;
            Global.status=1;
           MainFrame mf=new MainFrame();
            mf.setVisible(true);
                    dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
            jPasswordField_Pass1.setText("");
        } 
}
public void userLogin()
{
    String username=jTextField_User.getText();
        String password=new String(jPasswordField_Pass.getText());
        
          try
                          {
                               String pssword=password;
   MessageDigest md= MessageDigest.getInstance("MD5");
   byte[] hashInBytes =md.digest(pssword.getBytes(StandardCharsets.UTF_8));
   
   StringBuilder sb= new StringBuilder();
   for(byte b : hashInBytes)
   {
       sb.append(String.format("%02x", b));
      //System.out.println(sb.toString());
       password=sb.toString();
   }
   //System.out.println(password);
                          }
                          catch(Exception e)
                          {
                              System.out.println(e);
                          }
  ///Encrption
  
        Login u=new Login();
        u.setUsername(username);
        u.setPassword(password);
        LoginDUO uli=new LoginDUO();
        int count=uli.verifyUser(u);
        System.out.println(count);
        if(count>0)
        {
           
            JOptionPane.showMessageDialog(null,"Login Successful");
            Global.user=username;
            Global.uid=count;
                        Global.status=0;

          MainFrame mf=new MainFrame();
            mf.setVisible(true);
                    dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
            jPasswordField_Pass.setText("");
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanel_First = new javax.swing.JPanel();
        jButton_Admin = new javax.swing.JButton();
        jButton_User = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Admin = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_User1 = new javax.swing.JTextField();
        jPasswordField_Pass1 = new javax.swing.JPasswordField();
        jButton_Login2 = new javax.swing.JButton();
        jButton_Back2 = new javax.swing.JButton();
        jPanel_User = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_User = new javax.swing.JTextField();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy");
        setBackground(new java.awt.Color(20, 130, 220));
        setPreferredSize(new java.awt.Dimension(1360, 720));

        jPanel_Main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Main.setPreferredSize(new java.awt.Dimension(1290, 672));
        jPanel_Main.setLayout(new java.awt.CardLayout());

        jPanel_First.setBackground(new java.awt.Color(20, 130, 220));
        jPanel_First.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 130, 220), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2)));
        jPanel_First.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel_First.setPreferredSize(new java.awt.Dimension(1290, 672));

        jButton_Admin.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Admin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Admin.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Admin.setText("ADMIN");
        jButton_Admin.setBorder(null);
        jButton_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdminActionPerformed(evt);
            }
        });

        jButton_User.setBackground(new java.awt.Color(255, 255, 0));
        jButton_User.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_User.setForeground(new java.awt.Color(102, 0, 102));
        jButton_User.setText("USER");
        jButton_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN AS");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("        Or");

        javax.swing.GroupLayout jPanel_FirstLayout = new javax.swing.GroupLayout(jPanel_First);
        jPanel_First.setLayout(jPanel_FirstLayout);
        jPanel_FirstLayout.setHorizontalGroup(
            jPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FirstLayout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addGroup(jPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(jPanel_FirstLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_FirstLayout.setVerticalGroup(
            jPanel_FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FirstLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_User)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Main.add(jPanel_First, "pnlCard");

        jPanel_Admin.setBackground(new java.awt.Color(20, 130, 220));
        jPanel_Admin.setPreferredSize(new java.awt.Dimension(1290, 672));

        jPanel7.setBackground(new java.awt.Color(20, 130, 220));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PASSWORD");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter ID");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("USERNAME");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 40));

        jTextField_User1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(jTextField_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 40));

        jPasswordField_Pass1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(jPasswordField_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 40));

        jButton_Login2.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Login2.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jButton_Login2.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Login2.setText("Sign In");
        jButton_Login2.setBorder(null);
        jButton_Login2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_Login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, 40));

        jButton_Back2.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Back2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Back2.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Back2.setText("BACK");
        jButton_Back2.setBorder(null);
        jButton_Back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AdminLayout = new javax.swing.GroupLayout(jPanel_Admin);
        jPanel_Admin.setLayout(jPanel_AdminLayout);
        jPanel_AdminLayout.setHorizontalGroup(
            jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdminLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(610, 610, 610))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Back2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_AdminLayout.setVerticalGroup(
            jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdminLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Back2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Main.add(jPanel_Admin, "pnlCard2");

        jPanel_User.setBackground(new java.awt.Color(20, 130, 220));
        jPanel_User.setPreferredSize(new java.awt.Dimension(1290, 672));

        jPanel2.setBackground(new java.awt.Color(20, 130, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USERNAME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 40));

        jTextField_User.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextField_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 40));

        jPasswordField_Pass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jPasswordField_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 40));

        jButton_Login.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Login.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Login.setText("Sign In");
        jButton_Login.setBorder(null);
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, 40));

        jButton_Back.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Back.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(102, 0, 102));
        jButton_Back.setText("BACK");
        jButton_Back.setBorder(null);
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_UserLayout = new javax.swing.GroupLayout(jPanel_User);
        jPanel_User.setLayout(jPanel_UserLayout);
        jPanel_UserLayout.setHorizontalGroup(
            jPanel_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UserLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(610, 610, 610))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_UserLayout.setVerticalGroup(
            jPanel_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UserLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Main.add(jPanel_User, "pnlCard3");

        jPanel5.setBackground(new java.awt.Color(20, 130, 220));
        jPanel5.setPreferredSize(new java.awt.Dimension(1290, 672));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_Main.add(jPanel5, "pnlCard4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdminActionPerformed
c.show(jPanel_Main, "pnlCard2");

    }//GEN-LAST:event_jButton_AdminActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
c.first(jPanel_Main);
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
 userLogin();
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton_Login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login2ActionPerformed
adminLogin();
    }//GEN-LAST:event_jButton_Login2ActionPerformed

    private void jButton_Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back2ActionPerformed
c.first(jPanel_Main);
    }//GEN-LAST:event_jButton_Back2ActionPerformed

    private void jButton_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UserActionPerformed
c.show(jPanel_Main, "pnlCard3");
    }//GEN-LAST:event_jButton_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Admin;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Back2;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Login2;
    private javax.swing.JButton jButton_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Admin;
    private javax.swing.JPanel jPanel_First;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_User;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JPasswordField jPasswordField_Pass1;
    private javax.swing.JTextField jTextField_User;
    private javax.swing.JTextField jTextField_User1;
    // End of variables declaration//GEN-END:variables
}
